version: '3'
services:
  db:
    build:
      context: ./homizor-database
      dockerfile: Dockerfile
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
     - POSTGRES_USER=myuser
     - POSTGRES_PASSWORD=mypassword
     - POSTGRES_DB=postgres
  backend:
    build:
      context: ./homizor-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
  frontend:
    build:
      context: ./homizor-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend